version: '2'

services:
  web-pozos:
    image: php:apache
    ports:
      - "80:80"
    volumes:
      - ./website:/var/www/html
    environment:
      - USERNAME=toto
      - PASSWORD=python
    networks:
      - api-pozos

  api-student:
    image: api-student:1
    ports:
      - "3000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - api-pozos

networks:
  api-pozos:
